configured_endpoints: 31
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gbox%2Fgbox-sdk-fa953c0fa2e21f8cc2a0c1c8af2d3a3f1f80d4b4c89b68dbcc2af9d17b4ade90.yml
openapi_spec_hash: bf5640d2c9d7c5d46dcbff53689ae2d9
config_hash: dff637d9692ecee2da2bb3b333b2786c
