configured_endpoints: 49
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gbox%2Fgbox-sdk-e6dbb5a70011e7b1e6393f872539e82cdc13ba62ed3c6d13feafc4b15baa30ca.yml
openapi_spec_hash: 194cb9f7a25adba027a9db5d6bbaf57a
config_hash: 8f35dd56cc26cafb696c26e01fbd3962
