configured_endpoints: 23
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gbox%2Fgbox-sdk-f3df3e469dd8b079f68bf676c1b1d26fdabcdfee319f26d49c3ac8d2ab322c76.yml
openapi_spec_hash: 7adadeebe4a5bfbae1e6459d8424aa12
config_hash: 9c2fd1840ebe18b0ade5fed272c0825d
