configured_endpoints: 98
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gbox%2Fgbox-sdk-a898526d8764baa85f3d87fba8fc0dd0fc2898591f91f0485d597ef30704e830.yml
openapi_spec_hash: 0a4fa604e5ebba5dec7c7c863cf4bfc6
config_hash: df3dc1d8ddc97f105dddeec511b7dacc
