configured_endpoints: 98
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gbox%2Fgbox-sdk-18678eee3fbcdde6815d928382ca2c36170de130f03c0196d150bca8b95fd630.yml
openapi_spec_hash: 6ad31d84f2606de01bec00895bebccad
config_hash: df3dc1d8ddc97f105dddeec511b7dacc
